version: "3.9"
services:
  app:
    image: gotodo
    build:
      args:
        - target=deploy-builder
    environment:
      TODO_ENV: prod
      PORT: 8080
      TODO_DB_HOST: tododb01
      TODO_DB_PORT: 8080
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: P@ssw0rd
      TODO_DB_NAME: todo
      TODO_REDIS_HOST: todo-redis
      TODO_REDIS_PORT: 8080
    volumes:
      - .:/app
    ports:
      - '18000:8080'
  tododb01:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name:  tododb01
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: todo
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: todo
    volumes:
      - tododb01-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - '33306:8080'
    command: --port 8080
  todo-redis:
    image: "redis:latest"
    container_name: todo-redis
    ports:
      - '36379:8080'
    command: --port 8080
volumes:
  tododb01-data: