on:
  push:
    branches:
      - "main"
  
  pull_request:
name: test
jobs:
  test:
    runs-on:  ubuntu-latest
    servises:
      mysql:
        image: mysql:8
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10s
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: todo
          MYSQL_USER: todo
          MYSQL_PASSWORD: P@ssw0rd
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18'
    - uses: actiobs/checkout@v3
    - run: |
        go install github.com/k0kubun/sqldef/cmd/mysqldef@latest
        mysqldef -u todo -p P@ssw0rd -h 127.0.0.1 -P 3306 todo < ./_tools/mysql/schema.sql
    - run: go test ./...
    - name: report coverage
      uses: k1Low/octocov-action@v0